{{- if and (not .Values.secrets.aws.existingSecret) (or .Values.secrets.aws.accessKeyId .Values.secrets.aws.secretAccessKey) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spillway.fullname" . }}-aws
  labels:
    {{- include "spillway.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.aws.accessKeyId }}
  AWS_ACCESS_KEY_ID: {{ .Values.secrets.aws.accessKeyId | quote }}
  {{- end }}
  {{- if .Values.secrets.aws.secretAccessKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.secrets.aws.secretAccessKey | quote }}
  {{- end }}
  {{- if .Values.secrets.aws.region }}
  AWS_REGION: {{ .Values.secrets.aws.region | quote }}
  {{- end }}
  {{- if .Values.secrets.aws.hostedZoneId }}
  AWS_HOSTED_ZONE_ID: {{ .Values.secrets.aws.hostedZoneId | quote }}
  {{- end }}
---
{{- end }}
{{- if and (not .Values.secrets.tailscale.existingSecret) .Values.secrets.tailscale.authKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spillway.fullname" . }}-tailscale
  labels:
    {{- include "spillway.labels" . | nindent 4 }}
type: Opaque
stringData:
  TS_AUTHKEY: {{ .Values.secrets.tailscale.authKey | quote }}
{{- end }}
